### ISSUE TITLE
I have a problem 

### ISSUE THREAD

**Issue by fantajeon** [kaishengtai/torch-ntm#6]
I'v tested NTM(copy.lua), and replaced input with my own data form as follows:
-- NTM config
local config = {
  input_dim = 2,
  output_dim = 1,
  mem_rows = 128,
  mem_cols = 20,
  cont_dim = 100
}.

However, I encounted a error....

/home/digits/torch/install/bin/luajit: ...e/digits/torch/install/share/lua/5.1/nngraph/gmodule.lua:321: inconsistent tensor size at /home/digits/torch/extra/nn/generic/Sigmoid.c:27
stack traceback:
    [C]: in function 'updateGradInput'
    ...e/digits/torch/install/share/lua/5.1/nngraph/gmodule.lua:321: in function 'neteval'
    ...e/digits/torch/install/share/lua/5.1/nngraph/gmodule.lua:355: in function 'updateGradInput'
    /home/digits/torch/install/share/lua/5.1/nn/Module.lua:30: in function 'backward'
    /home/digits/workspace/git/torch-ntm2/NTM.lua:384: in function 'backward'
    tasks/my.lua:216: in function 'backward'
    tasks/my.lua:281: in function 'opfunc'
    /home/digits/workspace/git/torch-ntm2/rmsprop.lua:26: in function 'rmsprop'
    tasks/my.lua:303: in main chunk
    [C]: in function 'dofile'
    ...gits/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x00406670

Could tell me how to solve this problem?

**Comment by vseledkin** [comment]
Probably this relates https://github.com/kaishengtai/torch-ntm/pull/2/files code doesnt support unequality of input and output size

**Comment by fantajeon** [comment]
Yes, I tested the code(https://github.com/kaishengtai/torch-ntm/pull/2/files), but same problem. I have a good idea, that is, just extra dimension  was zero padding. Thank you. :)
