### ISSUE TITLE
Error: attempt to call global 'unpack' (a nil value)

### ISSUE THREAD

**Issue by inexxt** [kaishengtai/torch-ntm#9]
When I try to get the copy.lua task working, the following error appears:

<pre>
/home/jack/torch/install/bin/lua: /home/jack/torch/install/share/lua/5.2/nngraph/node.lua:58: attempt to call global 'unpack' (a nil value)
stack traceback:
        /home/jack/torch/install/share/lua/5.2/nngraph/node.lua:58: in function 'split'
        /home/jack/torch/install/share/lua/5.2/nngraph/gmodule.lua:71: in function '__init'
        /home/jack/torch/install/share/lua/5.2/torch/init.lua:91: in function </home/jack/torch/install/share/lua/5.2/torch/init.lua:87>
        [C]: in function 'gModule'
        /home/jack/Neurons/torch-ntm/NTM.lua:174: in function 'new_cell'
        /home/jack/Neurons/torch-ntm/NTM.lua:40: in function '__init'
        /home/jack/torch/install/share/lua/5.2/torch/init.lua:91: in function </home/jack/torch/install/share/lua/5.2/torch/init.lua:87>
        [C]: in function 'NTM'
        tasks/copy.lua:91: in main chunk
        [C]: in function 'dofile'
        ...jack/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:133: in main chunk
        [C]: in ?
</pre>

I've tried to run it with lua5.1 and 5.2 with the same result. I've also tried to run it on fresh docker container - same effect (all systems were ubuntu).

**Comment by soumith** [comment]
fixed the issue.

luarocks install nngraph

that will fix it.

**Comment by kaishengtai** [comment]
Great. Thanks, Soumith.

**Comment by Malhabib** [comment]
home/alhabib/torch/install/bin/lua: ./densecap/LocalizationLayer.lua:653: attempt to call global 'unpack' (a nil value)
stack traceback:
	./densecap/LocalizationLayer.lua:653: in function 'build_rpn'
	./densecap/LocalizationLayer.lua:95: in function '__init'
	/home/alhabib/torch/install/share/lua/5.2/torch/init.lua:91: in function </home/alhabib/torch/install/share/lua/5.2/torch/init.lua:87>
	[C]: in function 'LocalizationLayer'
	./densecap/DenseCapModel.lua:84: in function '__init'
	/home/alhabib/torch/install/share/lua/5.2/torch/init.lua:91: in function </home/alhabib/torch/install/share/lua/5.2/torch/init.lua:87>
	[C]: in function 'DenseCapModel'
	./models.lua:7: in function 'setup'
	train.lua:48: in main chunk
	[C]: in function 'dofile'
	...abib/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?
May you help please
